"""add resumo

Revision ID: 29aba3ef2cdb
Revises: cc34848f4654
Create Date: 2024-10-28 11:26:10.069303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29aba3ef2cdb'
down_revision = 'cc34848f4654'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticias', schema=None) as batch_op:
        batch_op.drop_column('resume')

    # ### end Alembic commands ###
