"""empty message

Revision ID: 8877e5f9d235
Revises: f62cbdfeb4fe
Create Date: 2024-11-06 21:38:51.724762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8877e5f9d235'
down_revision = 'f62cbdfeb4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('date_joined')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
