"""aumentei numero de caracteres no image_link e pfp_image

Revision ID: f62cbdfeb4fe
Revises: 0f17d0b6b735
Create Date: 2024-11-02 10:15:33.829407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62cbdfeb4fe'
down_revision = '0f17d0b6b735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('profile_pic',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
